/** 来源：诺心蛋糕甄选列表页（解析生成，非实时接口） */
export type CakeItem = {
  /** 商品名称 */
  name: string;
  /** 站内静态路径 */
  img: string;
  /** 列表价展示，如 ¥218/约454g */
  price: string;
  taste: number;
  norms: number;
};

export const cakeList: CakeItem[] = [
  {
    name: '雪域牛乳芝士',
    img: '/cake/xynrzs.jpg',
    price: '¥218/约454g',
    taste: 1,
    norms: 2,
  },
  {
    name: '白月光',
    img: '/cake/byg.jpg',
    price: '¥288/约468g',
    taste: 4,
    norms: 1,
  },
  {
    name: '穆萨耶夫·闪耀',
    img: '/cake/msyfsy.jpg',
    price: '¥288/约490g',
    taste: 4,
    norms: 2,
  },
  {
    name: '瑰丽绽放',
    img: '/cake/glzf.jpg',
    price: '¥288/约480g',
    taste: 4,
    norms: 1,
  },
  {
    name: '来财',
    img: '/cake/lc.jpg',
    price: '¥288/约530g',
    taste: 4,
    norms: 2,
  },
  {
    name: '星芒礼赞·金牛座',
    img: '/cake/xmlzjnz.jpg',
    price: '¥258/约415g',
    taste: 5,
    norms: 1,
  },
  {
    name: '星梦城堡',
    img: '/cake/xmcb.jpg',
    price: '¥288/约454g',
    taste: 4,
    norms: 3,
  },
  {
    name: '福禄祝寿',
    img: '/cake/flzs.jpg',
    price: '¥288/约468g',
    taste: 4,
    norms: 3,
  },
  {
    name: '金葫耀财',
    img: '/cake/jhyc.jpg',
    price: '¥288/约460g',
    taste: 4,
    norms: 1,
  },
  {
    name: '淡雪莓莓',
    img: '/cake/dxmm.jpg',
    price: '¥258/约550g',
    taste: 4,
    norms: 2,
  },
  {
    name: '巧遇莓好',
    img: '/cake/qymh.jpg',
    price: '¥258/约580g',
    taste: 4,
    norms: 1,
  },
  {
    name: '环游世界',
    img: '/cake/hysj.jpg',
    price: '¥258/约454g',
    taste: 3,
    norms: 2,
  },
  {
    name: '巳事如意',
    img: '/cake/ssry.jpg',
    price: '¥218/约360g',
    taste: 3,
    norms: 1,
  },
  {
    name: '梦幻星云',
    img: '/cake/mhxy.jpg',
    price: '¥218/约460g',
    taste: 5,
    norms: 2,
  },
  {
    name: '“嘭”然心动',
    img: '/cake/prxd.jpg',
    price: '¥218/约380g',
    taste: 5,
    norms: 1,
  },
  {
    name: '四拼悠乐',
    img: '/cake/spyl.jpg',
    price: '¥218/约454g',
    taste: 3,
    norms: 4,
  },
  {
    name: '锦鲤送福',
    img: '/cake/jlsf.jpg',
    price: '¥258/约460g',
    taste: 1,
    norms: 2,
  },
  {
    name: '春漾莓光',
    img: '/cake/cymg.jpg',
    price: '¥218/约440g',
    taste: 4,
    norms: 4,
  },
  {
    name: '屿夏金芒',
    img: '/cake/yxjm.jpg',
    price: '¥218/约435g',
    taste: 5,
    norms: 4,
  },
  {
    name: '蜜瓜轻甜',
    img: '/cake/mgqt.jpg',
    price: '¥218/约448g',
    taste: 4,
    norms: 2,
  },
  {
    name: '青绮「猕」漾',
    img: '/cake/qqmy.jpg',
    price: '¥218/约472g',
    taste: 5,
    norms: 4,
  },
  {
    name: '菠萝旖旎',
    img: '/cake/blyn.jpg',
    price: '¥218/约460g',
    taste: 4,
    norms: 2,
  },
  {
    name: '咖啡沃鲁托',
    img: '/cake/kfwlt.jpg',
    price: '¥218/约555g',
    taste: 5,
    norms: 4,
  },
  {
    name: '芋你啵啵',
    img: '/cake/ynbb.jpg',
    price: '¥218/约515g',
    taste: 5,
    norms: 2,
  },
  {
    name: '提拉米苏',
    img: '/cake/tlms.jpg',
    price: '¥218/约460g',
    taste: 3,
    norms: 4,
  },
  {
    name: '臻巧四重奏',
    img: '/cake/zqszz.jpg',
    price: '¥218/约480g',
    taste: 3,
    norms: 2,
  },
  {
    name: '草莓云霓',
    img: '/cake/cmyn.jpg',
    price: '¥168/约355g',
    taste: 4,
    norms: 3,
  },
  {
    name: '蓝莓雪绒',
    img: '/cake/lmxr.jpg',
    price: '¥168/约320g',
    taste: 6,
    norms: 2,
  },
  {
    name: '悠然桃桃',
    img: '/cake/yrtt.jpg',
    price: '¥168/约375g',
    taste: 6,
    norms: 2,
  },
  {
    name: '浮云莓恋',
    img: '/cake/fyml.jpg',
    price: '¥258/约454g',
    taste: 6,
    norms: 3,
  },
  {
    name: '日进斗金',
    img: '/cake/rjdj.jpg',
    price: '¥398/约908g',
    taste: 2,
    norms: 2,
  },
  {
    name: '请发财',
    img: '/cake/qfc.jpg',
    price: '¥258/约300g',
    taste: 4,
    norms: 3,
  },
  {
    name: '日富一日',
    img: '/cake/rfyr.jpg',
    price: '¥398/约908g',
    taste: 2,
    norms: 2,
  },
  {
    name: '春·茶墨画',
    img: '/cake/ccmh.jpg',
    price: '¥218/约400g',
    taste: 4,
    norms: 3,
  },
  {
    name: '法式松露黑巧',
    img: '/cake/fsslhq.jpg',
    price: '¥218/约454g',
    taste: 3,
    norms: 2,
  },
  {
    name: '雪松秘境',
    img: '/cake/xsmj.jpg',
    price: '¥218/约454g',
    taste: 3,
    norms: 3,
  },
  {
    name: '黑森林可可',
    img: '/cake/hslkk.jpg',
    price: '¥218/约454g',
    taste: 3,
    norms: 2,
  },
];
